


Imports System.Drawing
Imports System.Configuration
Imports System.IO
Imports System.Text
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections.Generic
Imports System.Web
Imports System.Web.Mvc




Partial Class PaginaBase
    Inherits System.Web.UI.Page
    Protected Sub BtnConsulta_Click(sender As Object, e As EventArgs) Handles BtnConsulta.Click
        Label1.Text = DropDownList1.Text
        Dim Entidad As String
        Dim F1 As String
        Dim F2 As String
        F1 = TextFechaIni0.Text
        F2 = TextFechaFin.Text
        F1 = F1 + " 00:00:00"
        F2 = F2 + " 23:59:59"
        Entidad = DropDownList1.Text
        '  SqlDataSource1.SelectCommand = "SELECT DISTINCT GENDETCON.GDECODIGO AS Regimen, GENDETCON.GDENOMBRE AS Entidad, (SELECT GASCODIGO FROM GENARESER AS g WHERE (OID = (SELECT TOP (1) HCNFOLIO.GENARESER FROM HCNSOLEXA INNER JOIN HCNRESEXA ON HCNSOLEXA.HCNRESEXA = HCNRESEXA.OID INNER JOIN HCNFOLIO ON HCNSOLEXA.HCNFOLIO = HCNFOLIO.OID INNER JOIN HCNFOLORDSRV ON HCNFOLIO.OID = HCNFOLORDSRV.HCNFOLIO INNER JOIN SLNORDSER ON HCNFOLORDSRV.SLNORDSER = SLNORDSER.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA.HCSESTADO = 1) ORDER BY HCNSOLEXA.HCSFECSOL DESC))) AS 'CodAreaSol', (SELECT GASNOMBRE FROM GENARESER AS g WHERE (OID = (SELECT TOP (1) HCNFOLIO_5.GENARESER FROM HCNSOLEXA AS HCNSOLEXA_5 INNER JOIN HCNRESEXA AS HCNRESEXA_5 ON HCNSOLEXA_5.HCNRESEXA = HCNRESEXA_5.OID INNER JOIN HCNFOLIO AS HCNFOLIO_5 ON HCNSOLEXA_5.HCNFOLIO = HCNFOLIO_5.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_5 ON HCNFOLIO_5.OID = HCNFOLORDSRV_5.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_6 ON HCNFOLORDSRV_5.SLNORDSER = SLNORDSER_6.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_6.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_5.HCSESTADO = 1) ORDER BY HCNSOLEXA_5.HCSFECSOL DESC))) AS 'Area Solicita', GENSERIPS.SIPCODIGO AS CodExamen, RTRIM(GENSERIPS.SIPNOMBRE) AS NomExamen, SLNSERPRO_base.SERCANTID AS Candtidad, CASE WHEN SLNSERPRO_base.SERAPLPRO = 1 THEN 'Si' ELSE 'No' END AS 'Procedimiento', CONVERT (decimal(11 , 0), SLNSERPRO_base.SERVALPRO) AS ValorUnitario, CONVERT (decimal(11 , 0), SLNSERPRO_base.SERVALENT * SLNSERPRO_base.SERCANTID) AS ValorTotServicio, SLNSERPRO_base.SERVALENT AS 'Valor Entidad', SLNSERPRO_base.SERVALPAC AS 'Valor Paciente', (SELECT TOP (1) HCNSOLEXA_4.HCSFECSOL FROM HCNSOLEXA AS HCNSOLEXA_4 INNER JOIN HCNRESEXA AS HCNRESEXA_4 ON HCNSOLEXA_4.HCNRESEXA = HCNRESEXA_4.OID INNER JOIN HCNFOLIO AS HCNFOLIO_4 ON HCNSOLEXA_4.HCNFOLIO = HCNFOLIO_4.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_4 ON HCNFOLIO_4.OID = HCNFOLORDSRV_4.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_5 ON HCNFOLORDSRV_4.SLNORDSER = SLNORDSER_5.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_5.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_4.HCSESTADO = 1) ORDER BY HCNSOLEXA_4.HCSFECSOL DESC) AS 'Fecha solicitud', (SELECT DISTINCT GMENOMCOM FROM GENMEDICO WHERE (OID = SLNSERPRO_base.GENMEDICO1)) AS Solicita, (SELECT DISTINCT GENESPECI.GEEDESCRI FROM GENMEDICO AS GENMEDICO_2 INNER JOIN GENESPMED ON GENMEDICO_2.OID = GENESPMED.MEDICOS INNER JOIN GENESPECI ON GENESPMED.ESPECIALIDADES = GENESPECI.OID WHERE (GENMEDICO_2.OID = SLNSERPRO_base.GENMEDICO1) AND (GENESPMED.GEMPRINCIPAL = 1)) AS Especialidad_Solicita, (SELECT TOP (1) GENMEDICO_1.GMENOMCOM FROM HCNSOLEXA AS HCNSOLEXA_3 INNER JOIN HCNRESEXA AS HCNRESEXA_3 ON HCNSOLEXA_3.HCNRESEXA = HCNRESEXA_3.OID INNER JOIN HCNFOLIO AS HCNFOLIO_3 ON HCNSOLEXA_3.HCNFOLIO = HCNFOLIO_3.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_3 ON HCNFOLIO_3.OID = HCNFOLORDSRV_3.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_4 ON HCNFOLORDSRV_3.SLNORDSER = SLNORDSER_4.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_4.OID = SLNSERPRO2.SLNORDSER1 INNER JOIN GENMEDICO AS GENMEDICO_1 ON HCNRESEXA_3.GENMEDICO = GENMEDICO_1.OID WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_3.HCSESTADO = 1) ORDER BY HCNSOLEXA_3.HCSFECSOL DESC) AS Realiza, (SELECT TOP (1) HCNRESEXA_2.HCRFECRES FROM HCNSOLEXA AS HCNSOLEXA_2 INNER JOIN HCNRESEXA AS HCNRESEXA_2 ON HCNSOLEXA_2.HCNRESEXA = HCNRESEXA_2.OID INNER JOIN HCNFOLIO AS HCNFOLIO_2 ON HCNSOLEXA_2.HCNFOLIO = HCNFOLIO_2.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_2 ON HCNFOLIO_2.OID = HCNFOLORDSRV_2.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_3 ON HCNFOLORDSRV_2.SLNORDSER = SLNORDSER_3.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_3.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_2.HCSESTADO = 1) ORDER BY HCNSOLEXA_2.HCSFECSOL DESC) AS 'Fecha Respuesta', GENARESER.GASCODIGO AS CodigoCentro, GENARESER.GASNOMBRE AS Centro, GENPACIEN.PACNUMDOC AS DocPaciente, GENPACIEN.PACPRIAPE + N' ' + GENPACIEN.PACSEGAPE + N' ' + GENPACIEN.PACPRINOM + N' ' + GENPACIEN.PACSEGNOM AS Paciente, CASE WHEN AINTIPING = 1 THEN 'Ambulatorio' ELSE 'Hospitalario' END AS TipoIngreso, CASE WHEN AINURGCON = 0 THEN 'Urgencias' ELSE 'Consulta Externa' END AS IngresoPor FROM INNCSUMPA INNER JOIN INNMSUMPA ON INNCSUMPA.OID = INNMSUMPA.INNCSUMPA RIGHT OUTER JOIN INNPRODUC INNER JOIN SLNPROHOJ ON INNPRODUC.OID = SLNPROHOJ.INNPRODUC1 ON INNMSUMPA.INNPRODUC = INNPRODUC.OID RIGHT OUTER JOIN SLNFACTUR INNER JOIN ADNINGRESO ON SLNFACTUR.ADNINGRESO = ADNINGRESO.OID INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID INNER JOIN GENDETCON ON SLNFACTUR.GENDETCON = GENDETCON.OID INNER JOIN GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID INNER JOIN GENTERCER ON GENCONTRA.GENTERCER1 = GENTERCER.OID INNER JOIN GEENENTADM ON GENCONTRA.DGNENTADM1 = GEENENTADM.OID INNER JOIN SLNCONHOJ ON ADNINGRESO.OID = SLNCONHOJ.ADNINGRES1 INNER JOIN SLNSERPRO AS SLNSERPRO_base ON ADNINGRESO.OID = SLNSERPRO_base.ADNINGRES1 INNER JOIN SLNORDSER AS SLNORDSER_2 ON SLNSERPRO_base.SLNORDSER1 = SLNORDSER_2.OID ON INNCSUMPA.SLNORDSER = SLNORDSER_2.OID AND SLNPROHOJ.OID = SLNSERPRO_base.OID LEFT OUTER JOIN SLNSERHOJ RIGHT OUTER JOIN GENSERIPS ON SLNSERHOJ.GENSERIPS1 = GENSERIPS.OID ON SLNSERPRO_base.OID = SLNSERHOJ.OID INNER JOIN GENARESER ON GENSERIPS.GENARESER1 = GENARESER.OID WHERE (SLNSERPRO_base.SERFECSER BETWEEN  '" + F1 + "' AND '" + F2 + "') AND (GENDETCON.GDECODIGO LIKE '%" + Entidad + "%')  AND ((SELECT TOP (1) HCNSOLEXA_1.HCSFECSOL FROM HCNSOLEXA AS HCNSOLEXA_1 INNER JOIN HCNRESEXA AS HCNRESEXA_1 ON HCNSOLEXA_1.HCNRESEXA = HCNRESEXA_1.OID INNER JOIN HCNFOLIO AS HCNFOLIO_1 ON HCNSOLEXA_1.HCNFOLIO = HCNFOLIO_1.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_1 ON HCNFOLIO_1.OID = HCNFOLORDSRV_1.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_1 ON HCNFOLORDSRV_1.SLNORDSER = SLNORDSER_1.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_1.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_1.HCSESTADO = 1)) IS NOT NULL) ORDER BY Regimen, 'CodAreaSol', CodExamen"
        ' GridView1.DataBind()
        Label2.Text = " del " + F1 + " al " + F2 + " " + GridView1.Rows.Count.ToString
    End Sub

    Protected Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click 'todas las entidades
        Dim EE As String = "%%"
        Label1.Text = EE
        Dim F1 As String
        Dim F2 As String
        F1 = TextFechaIni0.Text
        F2 = TextFechaFin.Text
        F1 = F1 + " 00:00:00"
        F2 = F2 + " 23:59:59"
        ' SqlDataSource1.SelectCommand = "SELECT DISTINCT GENDETCON.GDECODIGO AS Regimen, GENDETCON.GDENOMBRE AS Entidad, (SELECT GASCODIGO FROM GENARESER AS g WHERE (OID = (SELECT TOP (1) HCNFOLIO.GENARESER FROM HCNSOLEXA INNER JOIN HCNRESEXA ON HCNSOLEXA.HCNRESEXA = HCNRESEXA.OID INNER JOIN HCNFOLIO ON HCNSOLEXA.HCNFOLIO = HCNFOLIO.OID INNER JOIN HCNFOLORDSRV ON HCNFOLIO.OID = HCNFOLORDSRV.HCNFOLIO INNER JOIN SLNORDSER ON HCNFOLORDSRV.SLNORDSER = SLNORDSER.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA.HCSESTADO = 1) ORDER BY HCNSOLEXA.HCSFECSOL DESC))) AS 'CodAreaSol', (SELECT GASNOMBRE FROM GENARESER AS g WHERE (OID = (SELECT TOP (1) HCNFOLIO_5.GENARESER FROM HCNSOLEXA AS HCNSOLEXA_5 INNER JOIN HCNRESEXA AS HCNRESEXA_5 ON HCNSOLEXA_5.HCNRESEXA = HCNRESEXA_5.OID INNER JOIN HCNFOLIO AS HCNFOLIO_5 ON HCNSOLEXA_5.HCNFOLIO = HCNFOLIO_5.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_5 ON HCNFOLIO_5.OID = HCNFOLORDSRV_5.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_6 ON HCNFOLORDSRV_5.SLNORDSER = SLNORDSER_6.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_6.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_5.HCSESTADO = 1) ORDER BY HCNSOLEXA_5.HCSFECSOL DESC))) AS 'Area Solicita', GENSERIPS.SIPCODIGO AS CodExamen, RTRIM(GENSERIPS.SIPNOMBRE) AS NomExamen, SLNSERPRO_base.SERCANTID AS Candtidad, CASE WHEN SLNSERPRO_base.SERAPLPRO = 1 THEN 'Si' ELSE 'No' END AS 'Procedimiento', CONVERT (decimal(11 , 0), SLNSERPRO_base.SERVALPRO) AS ValorUnitario, CONVERT (decimal(11 , 0), SLNSERPRO_base.SERVALENT * SLNSERPRO_base.SERCANTID) AS ValorTotServicio, SLNSERPRO_base.SERVALENT AS 'Valor Entidad', SLNSERPRO_base.SERVALPAC AS 'Valor Paciente', (SELECT TOP (1) HCNSOLEXA_4.HCSFECSOL FROM HCNSOLEXA AS HCNSOLEXA_4 INNER JOIN HCNRESEXA AS HCNRESEXA_4 ON HCNSOLEXA_4.HCNRESEXA = HCNRESEXA_4.OID INNER JOIN HCNFOLIO AS HCNFOLIO_4 ON HCNSOLEXA_4.HCNFOLIO = HCNFOLIO_4.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_4 ON HCNFOLIO_4.OID = HCNFOLORDSRV_4.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_5 ON HCNFOLORDSRV_4.SLNORDSER = SLNORDSER_5.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_5.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_4.HCSESTADO = 1) ORDER BY HCNSOLEXA_4.HCSFECSOL DESC) AS 'Fecha solicitud', (SELECT DISTINCT GMENOMCOM FROM GENMEDICO WHERE (OID = SLNSERPRO_base.GENMEDICO1)) AS Solicita, (SELECT DISTINCT GENESPECI.GEEDESCRI FROM GENMEDICO AS GENMEDICO_2 INNER JOIN GENESPMED ON GENMEDICO_2.OID = GENESPMED.MEDICOS INNER JOIN GENESPECI ON GENESPMED.ESPECIALIDADES = GENESPECI.OID WHERE (GENMEDICO_2.OID = SLNSERPRO_base.GENMEDICO1) AND (GENESPMED.GEMPRINCIPAL = 1)) AS Especialidad_Solicita, (SELECT TOP (1) GENMEDICO_1.GMENOMCOM FROM HCNSOLEXA AS HCNSOLEXA_3 INNER JOIN HCNRESEXA AS HCNRESEXA_3 ON HCNSOLEXA_3.HCNRESEXA = HCNRESEXA_3.OID INNER JOIN HCNFOLIO AS HCNFOLIO_3 ON HCNSOLEXA_3.HCNFOLIO = HCNFOLIO_3.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_3 ON HCNFOLIO_3.OID = HCNFOLORDSRV_3.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_4 ON HCNFOLORDSRV_3.SLNORDSER = SLNORDSER_4.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_4.OID = SLNSERPRO2.SLNORDSER1 INNER JOIN GENMEDICO AS GENMEDICO_1 ON HCNRESEXA_3.GENMEDICO = GENMEDICO_1.OID WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_3.HCSESTADO = 1) ORDER BY HCNSOLEXA_3.HCSFECSOL DESC) AS Realiza, (SELECT TOP (1) HCNRESEXA_2.HCRFECRES FROM HCNSOLEXA AS HCNSOLEXA_2 INNER JOIN HCNRESEXA AS HCNRESEXA_2 ON HCNSOLEXA_2.HCNRESEXA = HCNRESEXA_2.OID INNER JOIN HCNFOLIO AS HCNFOLIO_2 ON HCNSOLEXA_2.HCNFOLIO = HCNFOLIO_2.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_2 ON HCNFOLIO_2.OID = HCNFOLORDSRV_2.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_3 ON HCNFOLORDSRV_2.SLNORDSER = SLNORDSER_3.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_3.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_2.HCSESTADO = 1) ORDER BY HCNSOLEXA_2.HCSFECSOL DESC) AS 'Fecha Respuesta', GENARESER.GASCODIGO AS CodigoCentro, GENARESER.GASNOMBRE AS Centro, GENPACIEN.PACNUMDOC AS DocPaciente, GENPACIEN.PACPRIAPE + N' ' + GENPACIEN.PACSEGAPE + N' ' + GENPACIEN.PACPRINOM + N' ' + GENPACIEN.PACSEGNOM AS Paciente, CASE WHEN AINTIPING = 1 THEN 'Ambulatorio' ELSE 'Hospitalario' END AS TipoIngreso, CASE WHEN AINURGCON = 0 THEN 'Urgencias' ELSE 'Consulta Externa' END AS IngresoPor FROM INNCSUMPA INNER JOIN INNMSUMPA ON INNCSUMPA.OID = INNMSUMPA.INNCSUMPA RIGHT OUTER JOIN INNPRODUC INNER JOIN SLNPROHOJ ON INNPRODUC.OID = SLNPROHOJ.INNPRODUC1 ON INNMSUMPA.INNPRODUC = INNPRODUC.OID RIGHT OUTER JOIN SLNFACTUR INNER JOIN ADNINGRESO ON SLNFACTUR.ADNINGRESO = ADNINGRESO.OID INNER JOIN GENPACIEN ON ADNINGRESO.GENPACIEN = GENPACIEN.OID INNER JOIN GENDETCON ON SLNFACTUR.GENDETCON = GENDETCON.OID INNER JOIN GENCONTRA ON GENDETCON.GENCONTRA1 = GENCONTRA.OID INNER JOIN GENTERCER ON GENCONTRA.GENTERCER1 = GENTERCER.OID INNER JOIN GEENENTADM ON GENCONTRA.DGNENTADM1 = GEENENTADM.OID INNER JOIN SLNCONHOJ ON ADNINGRESO.OID = SLNCONHOJ.ADNINGRES1 INNER JOIN SLNSERPRO AS SLNSERPRO_base ON ADNINGRESO.OID = SLNSERPRO_base.ADNINGRES1 INNER JOIN SLNORDSER AS SLNORDSER_2 ON SLNSERPRO_base.SLNORDSER1 = SLNORDSER_2.OID ON INNCSUMPA.SLNORDSER = SLNORDSER_2.OID AND SLNPROHOJ.OID = SLNSERPRO_base.OID LEFT OUTER JOIN SLNSERHOJ RIGHT OUTER JOIN GENSERIPS ON SLNSERHOJ.GENSERIPS1 = GENSERIPS.OID ON SLNSERPRO_base.OID = SLNSERHOJ.OID INNER JOIN GENARESER ON GENSERIPS.GENARESER1 = GENARESER.OID WHERE (SLNSERPRO_base.SERFECSER BETWEEN '" + F1 + "' AND '" + F2 + "') AND ((SELECT TOP (1) HCNSOLEXA_1.HCSFECSOL FROM HCNSOLEXA AS HCNSOLEXA_1 INNER JOIN HCNRESEXA AS HCNRESEXA_1 ON HCNSOLEXA_1.HCNRESEXA = HCNRESEXA_1.OID INNER JOIN HCNFOLIO AS HCNFOLIO_1 ON HCNSOLEXA_1.HCNFOLIO = HCNFOLIO_1.OID INNER JOIN HCNFOLORDSRV AS HCNFOLORDSRV_1 ON HCNFOLIO_1.OID = HCNFOLORDSRV_1.HCNFOLIO INNER JOIN SLNORDSER AS SLNORDSER_1 ON HCNFOLORDSRV_1.SLNORDSER = SLNORDSER_1.OID INNER JOIN SLNSERPRO AS SLNSERPRO2 ON SLNORDSER_1.OID = SLNSERPRO2.SLNORDSER1 WHERE (SLNSERPRO2.OID = SLNSERPRO_base.OID) AND (HCNSOLEXA_1.HCSESTADO = 1)) IS NOT NULL) ORDER BY Regimen, 'CodAreaSol', CodExamen"

        '  GridView1.DataBind()

        Label2.Text = " del " + F1 + " al " + F2 + " " + GridView1.Rows.Count.ToString
    End Sub

    Protected Sub BtnExportar_Click(sender As Object, e As System.EventArgs) Handles BtnExportar.Click

        GridView1.AllowPaging = False
        GridView1.DataBind()

        Try


            Dim sb As StringBuilder = New StringBuilder()
            Dim sw As StringWriter = New StringWriter(sb)
            Dim htw As HtmlTextWriter = New HtmlTextWriter(sw)
            Dim pagina As Page = New Page
            Dim form = New HtmlForm
            GridView1.EnableViewState = False
            pagina.EnableEventValidation = False
            pagina.DesignerInitialize()
            pagina.Controls.Add(form)
            form.Controls.Add(GridView1)
            pagina.RenderControl(htw)
            Response.Clear()
            Response.Buffer = True
            Response.ContentType = "application/vnd.ms-excel"
            Response.AddHeader("Content-Disposition", "attachment;filename=Servicios.xls")
            Response.Charset = "UTF-8"

            Response.ContentEncoding = Encoding.Default
            Response.Write(sb.ToString())
            Response.End()
            'Try
        Catch ex As Exception

        End Try
        GridView1.AllowPaging = True



    End Sub

End Class
